jobs:
  upload-dags:
    name: Deploy to PRD
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: prd
      url: 'http//dev.myapp.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetches the entire history for push events and the correct depth for PRs
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Get changed Python files
        id: get_files
        run: |
          echo "Event name: ${{ github.event_name }}"
          # For pushes, compare the commit before the push with the current one.
          if [ "${{ github.event_name }}" == "push" ]; then
            FILES=$(git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} | grep '\.py$')
          # For pull requests, compare the head of the PR with its base.
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            FILES=$(git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '\.py$')
          fi
          
          # Use xargs to format the file list into a single line
          echo "files_to_upload=$(echo $FILES | xargs)" >> $GITHUB_OUTPUT

      - name: Prepare and upload modified files
        if: steps.get_files.outputs.files_to_upload != ''
        run: |
          echo "Files to upload: ${{ steps.get_files.outputs.files_to_upload }}"
          
          mkdir staging_dir
          
          # Use xargs to handle the list of files for the copy command
          echo "${{ steps.get_files.outputs.files_to_upload }}" | xargs -n 1 -I {} cp --parents {} staging_dir/
          
          echo "Uploading contents of staging_dir to GCS..."
          gcloud storage cp --recursive staging_dir/* gs://us-central1-cc-data-analyti-d9b71af5-bucket/dags/