name: Deploy Modified Airflow DAGs to GCS

on:
  push:
    branches:
      - main
    paths:
      - '**.py' # Optional: Only triggers the workflow if a .py file is changed

jobs:
  upload-dags:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read # Needs read access to checkout and diff the code
  deploy_prd:
    name: Deploy to PRD
    needs: [upload-dags]
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'http//dev.myapp.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetches the entire history, which is required to diff against the previous commit
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Get changed Python files
        id: get_files
        run: |
          # Compares the commit before the push with the current one, filters for .py files,
          # and exports the list of files as an output variable.
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' | xargs)
          echo "files_to_upload=${FILES}" >> $GITHUB_OUTPUT

      - name: Prepare and upload modified files
        # This step only runs if the 'files_to_upload' output from the previous step is not empty
        if: steps.get_files.outputs.files_to_upload != ''
        run: |
          echo "Files to upload: ${{ steps.get_files.outputs.files_to_upload }}"
          
          # Create a temporary staging directory
          mkdir staging_dir
          
          # Copy only the changed files into the staging directory, preserving their path structure
          for file in ${{ steps.get_files.outputs.files_to_upload }}; do
            cp --parents "$file" staging_dir/
          done
          
          # Use the gcloud CLI to upload the contents of the staging directory
          gcloud storage cp --recursive staging_dir/* gs://us-central1-cc-data-analyti-d9b71af5-bucket/dags/